<?php

namespace App\Http\Controllers;

use App\Models\InspectionSuite;
use Illuminate\Http\Request;

class CorrecaoController extends Controller
{
  //descricao da vistoria das suites
  public function vistoriaDasSuites()
  {
    $dados=[
      'LIGAR O AR CONDICIONADO NO INÍCIO DA VISTORIA. FUNCIONAMENTO PLENO',
      'FUNCIONAMENTO PLENO DAS FECHADURAS (PRINCIPALMENTE MAÇANETAS) ?',
      'FUNCIONAMENTO PLENO DAS PORTAS (PRINCIPALMENTE NA PARTE INFERIOR) ?',
      'FUNCIONAMENTO PLENO DAS DOBRADIÇAS ?',
      'OS PISOS E REJUNTE ESTÃO SEM PRESENÇA DE MANCHAS, RACHADURAS OU REJUNTE SOLTANDO?',
      'PINTURA DAS PAREDES, PORTAS, AO REDOR DE TOMADAS E INTERRUPTORES ESTÃO SEM MANCHAS, BURACOS, INFILTRAÇÃO ?',
      'FUNCIONAMENTO PLENO DE TODA ILUMINAÇÃO (TROCA DAS LÂMPADAS E REATORES) ?',
      'FUNCIONAMENTO PLENO E LIMPEZA DOS INTERRUPTORES E TOMADAS ?',
      'FUNCIONAMENTO PLENO DA TELEVISÃO E DOS CANAIS ?',
      'FUNCIONAMENTO PLENO DO PAINEL DE CONTROLE ( MANUTENÇÃO, TROCA DE BOTÕES OU MANUTENÇÃO NA INSTALAÇÃO ELÉTRICA) ?',
      'FUNCIONAMENTO PLENO E LIMPEZA DO TELEFONE ?',
      'FUNCIONAMENTO PLENO DA CAMPAINHA?',
      'BOM ESTADO DE CONSERVAÇÃO E ASPECTO VISUAL DA ROUPA DE CAMA ?',
      'BOM ESTADO DE CONSERVAÇÃO E ASPECTO VISUAL DOS MOBILIÁRIOS ?',
      'BOM ESTADO DE CONSERVAÇÃO DO PAPEL DE PAREDE ? ( INDICAR QUANDO HOUVER NECESSIDADE DA TROCA)',
      'BOM ESTADO DE CONSERVAÇÃO E USO DAS CORTINAS ?',
      'BOM ESTADO DE CONSERVAÇÃO E USO DO ESPELHO ?',
      'ESTÁ OCORRENDO INFILTRAÇÃO OU CONDENSAÇÃO DO AR CONDICIONADO ?',
      'APOS TODAS AS CONFERÊNCIAS, DESLIGAR O AR CONDICIONADO E ANALISAR SEU DESEMPENHO. FUNCIONAMENTO PLENO ?',
      'FUNCIONAMENTO PLENO DO AQUECIMENTO DA ÁGUA DO CHUVEIRO E DA HIDROMASSAGEM?',
      'FEITA LIMPEZA DOS CHUVEIROS?',
      'ACABAMENTO DO FORRO SEM PROBLEMAS (PRINCIPALMENTE ONDE TEM UMIDADE)?',
      'BOM ESTADO DE CONSERVAÇÃO DAS SABONETEIRAS, LIXEIRA, REGISTROS, TORNEIRAS E DOS DEMAIS METAIS DO BANHEIRO?',
      'CORRETO FUNCIONAMENTO DOS RALOS?',
      'CORRETO FUNCIONAMENTO DA DESCARGA DOS VASOS SANITARIOS?',
      'VEDAÇÃO AO REDOR DOS VASOS SANITÁRIOS?',
      'INFILTRAÇÃO OU MANCHAS DE MOFO NOS BANHEIROS ?',
    ];


    $inspectionSuites = InspectionSuite::get();

    foreach ($inspectionSuites as $inspectionSuite) {
      $itens = $inspectionSuite->inspection_suite_items;
     
      foreach ($itens as $key=>$item) {
               
        $item->description = $dados[$key];
        $item->save();
      }
    }


    dd('fim');
  }
}
